---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.oauth.name }}"
  labels:
    app: "{{ .Values.oauth.name }}"
spec:
  replicas: {{ .Values.oauth.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.oauth.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.oauth.name }}"
    spec:
      containers:
        - name: "{{ .Values.oauth.name }}"
          image: "{{ .Values.oauth.deployment.image }}:{{ .Values.oauth.deployment.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.oauth.deployment.port }}
          args:
            - --provider=github
            - --email-domain=*
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --cookie-secure=false
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: {{ .Values.oauth.env.clientID }}
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: {{ .Values.oauth.env.clientSecret }}
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: {{ .Values.oauth.env.cookieSecret }}
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: "{{ .Values.oauth.env.hostname }}/oauth2/callback"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.oauth.name }}"
spec:
  selector:
    app: "{{ .Values.oauth.name }}"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.oauth.deployment.port }}
