---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.oauth.env.domain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "{{ .Values.oauth.env.domain }}/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.webapp.name }}"
            port:
              number: {{ .Values.webapp.deployment.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.oauth.name }}"
            port:
              number: {{ .Values.oauth.deployment.port }}
